import React, { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { supabase } from '../utils/supabase.js'
import { Download, RotateCcw, History, Star, TrendingUp, ThumbsUp, Linkedin, Check } from 'lucide-react'
import './ResultsPage.css'

export default function ResultsPage() {
  const { sessionId } = useParams()
  const navigate = useNavigate()

  const [session, setSession] = useState(null)
  const [qas, setQas]         = useState([])
  const [loading, setLoading] = useState(true)
  const [copied, setCopied]   = useState(false)

  useEffect(() => {
    if (!sessionId) { navigate('/dashboard'); return }
    fetchData()
  }, [sessionId])

  async function fetchData() {
    setLoading(true)
    const { data: s, error: sErr } = await supabase
      .from('interview_sessions')
      .select('*')
      .eq('id', sessionId)
      .single()

    if (sErr || !s) { navigate('/dashboard'); return }
    setSession(s)

    const { data: qa } = await supabase
      .from('interview_qa')
      .select('*')
      .eq('session_id', sessionId)
      .order('question_number', { ascending: true })

    setQas(qa || [])
    setLoading(false)
  }

  if (loading) return <div className="full-loader"><div className="spinner-lg" /></div>
  if (!session) return null

  const avgScore   = session.overall_score || '0.0'
  const avgComm    = session.communication_score || 0
  const avgTech    = session.technical_score || 0
  const avgConf    = session.confidence_score || 0
  const avgClarity = session.clarity_score || 0
  const answered   = qas.filter(q => q.score > 0).length

  // Build strengths/improvements from saved per-question feedback
  const strengths    = [...new Set(qas.map(q => q.strength).filter(Boolean))].slice(0, 4)
  const improvements = [...new Set(qas.map(q => q.improvement).filter(Boolean))].slice(0, 4)

  const scoreColor = s => parseFloat(s) >= 7 ? 'var(--success)' : parseFloat(s) >= 5 ? 'var(--primary)' : 'var(--danger)'

  function buildReportText() {
    const divider = '─'.repeat(60)
    let txt = `InterviewAI — Final Report\n${divider}\n`
    txt += `Role: ${session.role}  |  Mode: ${session.mode}  |  Level: ${session.difficulty}\n`
    txt += `Date: ${new Date(session.completed_at || session.created_at).toLocaleDateString('en-IN')}\n${divider}\n\n`
    txt += `OVERALL SCORE: ${avgScore}/10\n`
    txt += `Communication: ${avgComm}/10  |  Technical: ${avgTech}/10  |  Confidence: ${avgConf}/10  |  Clarity: ${avgClarity}/10\n\n`
    txt += `Strengths:\n${strengths.map(s => `  • ${s}`).join('\n')}\n\n`
    txt += `Areas to Improve:\n${improvements.map(s => `  • ${s}`).join('\n')}\n\n`
    txt += `\nQUESTION-BY-QUESTION REVIEW\n${divider}\n`
    qas.forEach((q, i) => {
      txt += `\nQ${i + 1}${q.is_followup ? ' (Follow-up)' : ''}: ${q.question}\n`
      txt += `Answer: ${q.user_answer}\n`
      txt += `Score: ${q.score || 0}/10\n`
      txt += `Feedback: ${q.feedback_summary || ''}\n`
    })
    txt += `\n${divider}\nGenerated by InterviewAI\n`
    return txt
  }

  function downloadReport() {
    const blob = new Blob([buildReportText()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `InterviewAI_Report_${session.role.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  function shareLinkedIn() {
    const text = `I just scored ${avgScore}/10 in a ${session.role} mock interview on InterviewAI! 🎯\nCommunication: ${avgComm}/10 | Technical: ${avgTech}/10 | Confidence: ${avgConf}/10\n#InterviewPrep #CareerGrowth`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
    window.open('https://www.linkedin.com/feed/?shareActive=true', '_blank')
  }

  return (
    <div className="page-wrap">
      {/* ── Hero Score ── */}
      <div className="card res-hero">
        <div className="res-score-wrap">
          <div className="res-big-score" style={{ color: scoreColor(avgScore) }}>{avgScore}</div>
          <div className="res-score-label">out of 10</div>
        </div>
        <div className="res-hero-info">
          <h1 className="res-title">Interview Complete! 🎉</h1>
          <p className="res-role">{session.role} — {session.mode} — {session.difficulty}</p>
          <div className="res-metrics">
            <div className="res-metric"><span className="res-metric-val">{avgComm}/10</span><span className="res-metric-lbl">Communication</span></div>
            <div className="res-metric"><span className="res-metric-val">{avgTech}/10</span><span className="res-metric-lbl">Technical</span></div>
            <div className="res-metric"><span className="res-metric-val">{avgConf}/10</span><span className="res-metric-lbl">Confidence</span></div>
            <div className="res-metric"><span className="res-metric-val">{answered}/{qas.length}</span><span className="res-metric-lbl">Answered</span></div>
          </div>
        </div>
      </div>

      {/* ── AI Report Summary ── */}
      <div className="card" style={{ marginTop: '1rem' }}>
        <h2 className="res-section-title">Report Summary</h2>
        <div className="res-two-col">
          <div className="res-list-box green">
            <h4><ThumbsUp size={14} /> Strengths</h4>
            {strengths.length ? strengths.map((s, i) => <p key={i}>✓ {s}</p>) : <p>No specific strengths recorded.</p>}
          </div>
          <div className="res-list-box amber">
            <h4><TrendingUp size={14} /> Areas to Improve</h4>
            {improvements.length ? improvements.map((s, i) => <p key={i}>→ {s}</p>) : <p>No specific improvements recorded.</p>}
          </div>
        </div>
      </div>

      {/* ── Q&A Review ── */}
      <div className="card" style={{ marginTop: '1rem' }}>
        <h2 className="res-section-title">Question-by-Question Review</h2>
        {qas.map((q, i) => (
          <div key={q.id} className="res-qa-item">
            <div className="res-qa-top">
              <span className="res-qa-num">Q{i + 1}{q.is_followup ? ' · Follow-up' : ''}</span>
              <span className={`badge ${q.score >= 7 ? 'badge-green' : q.score >= 5 ? 'badge-purple' : q.score > 0 ? 'badge-amber' : 'badge-red'}`}>
                <Star size={11} /> {q.score || 0}/10
              </span>
            </div>
            <p className="res-qa-q">{q.question}</p>
            <p className="res-qa-a">{q.user_answer?.substring(0, 200)}{q.user_answer?.length > 200 ? '…' : ''}</p>
            {q.feedback_summary && <p className="res-qa-fb">{q.feedback_summary}</p>}
            {q.strength && (
              <div className="res-qa-detail">
                <span className="green-text">✓ {q.strength}</span>
                {q.improvement && <span className="amber-text">→ {q.improvement}</span>}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* ── Actions ── */}
      <div className="res-actions">
        <button className="btn btn-outline" onClick={downloadReport}><Download size={16} /> Download Report</button>
        <button className="btn btn-outline" onClick={shareLinkedIn}>
          {copied ? <><Check size={16} /> Copied!</> : <><Linkedin size={16} /> Share on LinkedIn</>}
        </button>
        <button className="btn btn-outline" onClick={() => navigate('/history')}><History size={16} /> View History</button>
        <button className="btn btn-primary" onClick={() => navigate('/setup')}><RotateCcw size={16} /> New Interview</button>
      </div>
    </div>
  )
}